/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tsgsub;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author oubeichen
 */
public class MultiLanDialog extends javax.swing.JDialog {

    /**
     * Creates new form MultiLanDialog
     */
    public MultiLanDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //this.setLocationRelativeTo(null); 
        Reslist.setModel(new DefaultListModel());
        init();
    }

    private void init() {
        int i;
        totalstyles = Main.getAllstyle().size();
        for (i = 0; i < totalstyles; i++) {
            String tstring = Main.getAllstyle().get(i).toString();
            StyleComboBox.addItem(tstring);
            if (tstring.contains("中")) {
                StyleComboBox.setSelectedIndex(i);
            }
            StyleComboBox1.addItem(tstring);
            if (tstring.contains("日")) {
                StyleComboBox1.setSelectedIndex(i);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FindLength = new javax.swing.JTextField();
        isFindLength = new javax.swing.JCheckBox();
        isFindTimeCover = new javax.swing.JCheckBox();
        isFindOver = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        isFindMultiLine = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Reslist = new javax.swing.JList();
        Find = new javax.swing.JButton();
        isFindWrongStyle = new javax.swing.JCheckBox();
        StyleComboBox = new javax.swing.JComboBox();
        StyleComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        isFindMultiLanStylePro = new javax.swing.JCheckBox();
        isFindMultiLanTimePro = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("双语查错");

        FindLength.setText("30");
        FindLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindLengthActionPerformed(evt);
            }
        });

        isFindLength.setSelected(true);
        isFindLength.setText("查找字符串长度大于");

        isFindTimeCover.setSelected(true);
        isFindTimeCover.setText("查找时间轴覆盖(需要事先按时间顺序排序，并且只查找对中日样式对应行）");

        isFindOver.setSelected(true);
        isFindOver.setText("查找结束早于等于开始");

        jLabel1.setText("请选择中文样式的名称：");

        isFindMultiLine.setSelected(true);
        isFindMultiLine.setText("查找多行字幕（含有\\n）");

        Reslist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReslistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Reslist);

        Find.setText("查找错误");
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });

        isFindWrongStyle.setSelected(true);
        isFindWrongStyle.setText("查找不存在对应样式的字幕行");

        jLabel2.setText("请选择日文样式的名称：");

        jLabel3.setText("由于双语轴错误情况还是挺多的，所以免不了有缺漏或者多余。双击下面的错误可在主窗口定位对应行的字幕。");

        isFindMultiLanStylePro.setSelected(true);
        isFindMultiLanStylePro.setText("查找中日样式不符");

        isFindMultiLanTimePro.setSelected(true);
        isFindMultiLanTimePro.setText("查找中日时间轴不符");

        jLabel4.setText("请在AE中修改后重新打开，多次检查无错误后才可确保。还在不断完善，请见谅。");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(isFindWrongStyle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(isFindMultiLine))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(isFindLength)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FindLength, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(isFindOver)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(isFindMultiLanTimePro)
                                    .addComponent(isFindMultiLanStylePro)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(StyleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StyleComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(isFindTimeCover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Find)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(StyleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(StyleComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isFindWrongStyle)
                    .addComponent(isFindMultiLine)
                    .addComponent(isFindMultiLanStylePro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isFindLength)
                    .addComponent(FindLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isFindOver)
                    .addComponent(isFindMultiLanTimePro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isFindTimeCover)
                    .addComponent(Find))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FindLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindLengthActionPerformed

    private void ReslistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReslistMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            String temp = Reslist.getSelectedValue().toString();
            int selectedrow = Integer.parseInt(temp.split(":", 2)[0]);
            Main.setSelectedRow(selectedrow);
        }
    }//GEN-LAST:event_ReslistMouseClicked

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        // TODO add your handling code here:

        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss.S");
        Date tstart;
        Date tend;
        Date lastend;
        Date laststart;
        boolean havetofind = false;
        String zh = StyleComboBox.getSelectedItem().toString();
        String jp = StyleComboBox1.getSelectedItem().toString();
        int total = Main.getStarttime().size(), i;
        DefaultListModel dlm = (DefaultListModel) Reslist.getModel();
        dlm.setSize(0);
        for (i = 0; i < total; i++) {
            /*初始化一些数值开始*/
            String temp = Main.getContent().get(i).toString();//当前行内容
            String style = Main.getStyle().get(i).toString();//当前行样式
            try {
                tstart = sdf.parse(Main.getStarttime().get(i).toString());//当前行开始时间
                tend = sdf.parse(Main.getEndtime().get(i).toString());//当前行结束时间
            } catch (ParseException ex) {
                Logger.getLogger(SingLanDialog.class.getName()).log(Level.SEVERE, null, ex);
                javax.swing.JOptionPane.showMessageDialog(this, "第" + i + "行字幕时间格式有误", "错误", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (zh.equals(style) || jp.equals(style)) {
                havetofind = true;
            }
            /*初始化一些数值结束*/

            if (isFindLength.isSelected())//判断长度
            {
                int findlen;
                try {
                    findlen = Integer.parseInt(FindLength.getText().toString());
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "输入的数字有误", "错误", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (temp.length() > findlen) {
                    dlm.addElement((int) (i + 1) + ": 这一行字幕长度为" + temp.length() + "，超出限制");
                }
            }
            if (isFindMultiLine.isSelected())//判断多行
            {
                if (temp.contains("\\n") || temp.contains("\\N")) {
                    dlm.addElement((int) (i + 1) + ": 这一行字幕包含\"\\n\"，将会显示为多行");
                }
            }
            if (isFindWrongStyle.isSelected())//判断错误样式
            {
                int j;
                for (j = 0; j < totalstyles; j++) {
                    if (StyleComboBox.getItemAt(j).equals(style)) {
                        break;
                    }
                }
                if (j == totalstyles) {
                    dlm.addElement((int) (i + 1) + ": 这一行字幕所使用的样式不在样式表里");
                }
            }
            if (isFindOver.isSelected())//判断结束时间早于开始时间
            {
                if (tstart.compareTo(tend) >= 0) {
                    dlm.addElement((int) (i + 1) + ": 这一行字幕时间轴结束时间早于等于开始时间");
                }
            }
            if (havetofind) {//是双语样式
                if (isFindTimeCover.isSelected())//判断时间轴重叠
                {
                    int j = i - 1;
                    while (j >= 0 && !Main.getStyle().get(j).toString().equals(style)) {
                        j--;
                    }
                    if (j >= 0)//找到上一个同样式的字幕（理论上是往前两个）
                    {
                        try {
                            lastend = sdf.parse(Main.getEndtime().get(j).toString());
                        } catch (ParseException ex) {
                            Logger.getLogger(SingLanDialog.class.getName()).log(Level.SEVERE, null, ex);
                            javax.swing.JOptionPane.showMessageDialog(this, "文件第" + j + "行字幕时间格式有误", "错误", javax.swing.JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                        if (lastend.compareTo(tstart) > 0) {
                            dlm.addElement((int) (i + 1) + ": 这一行和紧接着的上一个" + style + "样式字幕时间轴有重叠");
                        }
                    }
                }
                int j = i + 1;//找下一行双语字幕（理论上样式应该不同）
                while (j < total && !Main.getStyle().get(j).toString().equals(jp) && !Main.getStyle().get(j).toString().equals(zh)) {
                    j++;
                }
                if (j < total)//找到了下一行双语字幕
                {
                    if (isFindMultiLanStylePro.isSelected())//判断双语轴的样式
                    {
                        if (Main.getStyle().get(j).toString().equals(style))//后面样式和这个样式一样
                        {
                            dlm.addElement((int) (i + 1) + ": 这一行字幕的双语样式同后面紧接着的一行双语样式是相同的");
                        }
                    }
                    if (isFindMultiLanTimePro.isSelected() && jp.equals(style))//日文则判断是否和后面的中文时间一致
                    {
                        try {
                            lastend = sdf.parse(Main.getEndtime().get(j).toString());
                            laststart = sdf.parse(Main.getStarttime().get(j).toString());
                        } catch (ParseException ex) {
                            Logger.getLogger(MultiLanDialog.class.getName()).log(Level.SEVERE, null, ex);
                            javax.swing.JOptionPane.showMessageDialog(this, "文件第" + j + "行字幕时间格式有误", "错误", javax.swing.JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                        if (!tstart.equals(laststart) || !tend.equals(lastend)) {
                            dlm.addElement((int) (i + 1) + ": 这一行日语的时间轴和后面同一句话中文的时间轴不一样");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_FindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiLanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiLanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiLanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiLanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MultiLanDialog dialog = new MultiLanDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Find;
    private javax.swing.JTextField FindLength;
    private javax.swing.JList Reslist;
    private javax.swing.JComboBox StyleComboBox;
    private javax.swing.JComboBox StyleComboBox1;
    private javax.swing.JCheckBox isFindLength;
    private javax.swing.JCheckBox isFindMultiLanStylePro;
    private javax.swing.JCheckBox isFindMultiLanTimePro;
    private javax.swing.JCheckBox isFindMultiLine;
    private javax.swing.JCheckBox isFindOver;
    private javax.swing.JCheckBox isFindTimeCover;
    private javax.swing.JCheckBox isFindWrongStyle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private int totalstyles;
}
